import { ThemeConfig, ThemeId } from './types';

export const themes: Record<ThemeId, ThemeConfig> = {
  blossom: {
    id: 'blossom',
    name: 'Blossom Pink',
    emoji: '🌸',
    bgMain: 'bg-[#FFF2F5]',
    bgCard: 'bg-white',
    bgCardHover: 'hover:bg-[#FFF8FA]',
    borderCard: 'border-[#F8D7DF]',
    textPrimary: 'text-[#4A2E35]',
    textSecondary: 'text-[#875C66]',
    textMuted: 'text-[#B59199]',
    accentPink: '#FF6B8B',
    accentPinkLight: '#FFE3E9',
    accentGreen: '#66BB6A',
    accentGold: '#FFB300',
    accentPurple: '#AB47BC',
    shadowColor: 'shadow-pink-100/60',
    bannerBg: 'bg-gradient-to-br from-[#FF758C] via-[#FF7EB3] to-[#FF8FA3]',
  },
  wood: {
    id: 'wood',
    name: 'Classic Desk',
    emoji: '🪵',
    bgMain: 'bg-[#F2E8DC]',
    bgCard: 'bg-[#FCF8F2]',
    bgCardHover: 'hover:bg-[#FFFDFB]',
    borderCard: 'border-[#E0D0BE]',
    textPrimary: 'text-[#4A3728]',
    textSecondary: 'text-[#7D6450]',
    textMuted: 'text-[#A8927E]',
    accentPink: '#E06D75',
    accentPinkLight: '#FCE6E8',
    accentGreen: '#709D68',
    accentGold: '#D89B38',
    accentPurple: '#8E6CA8',
    shadowColor: 'shadow-amber-900/10',
    bannerBg: 'bg-gradient-to-br from-[#8C5E3D] via-[#A3704C] to-[#BA845D]',
  },
  lavender: {
    id: 'lavender',
    name: 'Lavender Dream',
    emoji: '💜',
    bgMain: 'bg-[#F6F2FF]',
    bgCard: 'bg-white',
    bgCardHover: 'hover:bg-[#FAF7FF]',
    borderCard: 'border-[#E2D6FC]',
    textPrimary: 'text-[#382B4F]',
    textSecondary: 'text-[#6F5B8F]',
    textMuted: 'text-[#9F8EB8]',
    accentPink: '#BA68C8',
    accentPinkLight: '#F3E5F5',
    accentGreen: '#4DB6AC',
    accentGold: '#FFB74D',
    accentPurple: '#7E57C2',
    shadowColor: 'shadow-purple-100/60',
    bannerBg: 'bg-gradient-to-br from-[#7E57C2] via-[#9575CD] to-[#B39DDB]',
  },
  mint: {
    id: 'mint',
    name: 'Mint Meadow',
    emoji: '🌿',
    bgMain: 'bg-[#F0F9F5]',
    bgCard: 'bg-white',
    bgCardHover: 'hover:bg-[#F6FCF9]',
    borderCard: 'border-[#CCE8DB]',
    textPrimary: 'text-[#204535]',
    textSecondary: 'text-[#4D7563]',
    textMuted: 'text-[#82A895]',
    accentPink: '#FF708F',
    accentPinkLight: '#FFE5EC',
    accentGreen: '#38A169',
    accentGold: '#E6A23C',
    accentPurple: '#9C6ADE',
    shadowColor: 'shadow-emerald-100/60',
    bannerBg: 'bg-gradient-to-br from-[#2E8B57] via-[#3CB371] to-[#66CDAA]',
  },
  midnight: {
    id: 'midnight',
    name: 'Midnight Star',
    emoji: '🌙',
    bgMain: 'bg-[#181524]',
    bgCard: 'bg-[#231F33]',
    bgCardHover: 'hover:bg-[#2C2740]',
    borderCard: 'border-[#38324F]',
    textPrimary: 'text-[#F3EDFF]',
    textSecondary: 'text-[#B4A6CE]',
    textMuted: 'text-[#7B6E94]',
    accentPink: '#FF6584',
    accentPinkLight: '#3D2536',
    accentGreen: '#48BB78',
    accentGold: '#F6AD55',
    accentPurple: '#B794F4',
    shadowColor: 'shadow-black/50',
    bannerBg: 'bg-gradient-to-br from-[#2C1F4A] via-[#442E6E] to-[#653C8E]',
  },
};
