import { ThemeConfig, ThemeId } from './types';

export const themes: Record<ThemeId, ThemeConfig> = {
  blossom: {
    id: 'blossom',
    name: 'Terracotta Alabaster',
    emoji: '',
    bgMain: 'bg-[#FAF8F5]',
    bgCard: 'bg-white/90',
    bgCardHover: 'hover:bg-white',
    borderCard: 'border-white/80',
    textPrimary: 'text-[#2C2A29]',
    textSecondary: 'text-[#7A7571]',
    textMuted: 'text-[#96928E]',
    accentPink: '#C86D51',
    accentPinkLight: '#F5EBE6',
    accentGreen: '#5B8A72',
    accentGold: '#D97706',
    accentPurple: '#7B6B8D',
    shadowColor: 'shadow-[0px_8px_24px_rgba(44,42,41,0.04)] shadow-xl',
    bannerBg: 'bg-gradient-to-r from-[#C86D51] via-[#D8836A] to-[#E8ACA0]',
  },
  wood: {
    id: 'wood',
    name: 'Fintech Sand',
    emoji: '',
    bgMain: 'bg-[#FAF8F5]',
    bgCard: 'bg-[#FFFFFF]',
    bgCardHover: 'hover:bg-[#FAF9F6]',
    borderCard: 'border-[#E4E0DC]',
    textPrimary: 'text-[#2C2A29]',
    textSecondary: 'text-[#7A7571]',
    textMuted: 'text-[#9E948C]',
    accentPink: '#C86D51',
    accentPinkLight: '#F5EBE6',
    accentGreen: '#5B8A72',
    accentGold: '#D97706',
    accentPurple: '#7B6B8D',
    shadowColor: 'shadow-[0px_8px_24px_rgba(44,42,41,0.04)] shadow-xl',
    bannerBg: 'bg-gradient-to-r from-[#2C2A29] via-[#4A4542] to-[#6E645C]',
  },
  mint: {
    id: 'mint',
    name: 'Sage Eucalyptus',
    emoji: '',
    bgMain: 'bg-[#FAF8F5]',
    bgCard: 'bg-white',
    bgCardHover: 'hover:bg-[#F2F7F4]',
    borderCard: 'border-[#D1E5DB]',
    textPrimary: 'text-[#2C2A29]',
    textSecondary: 'text-[#5B8A72]',
    textMuted: 'text-[#7A7571]',
    accentPink: '#C86D51',
    accentPinkLight: '#F5EBE6',
    accentGreen: '#5B8A72',
    accentGold: '#D97706',
    accentPurple: '#7B6B8D',
    shadowColor: 'shadow-[0px_8px_24px_rgba(44,42,41,0.04)] shadow-xl',
    bannerBg: 'bg-gradient-to-r from-[#5B8A72] via-[#6D9E85] to-[#88B39D]',
  },
  lavender: {
    id: 'lavender',
    name: 'Dusky Lavender',
    emoji: '',
    bgMain: 'bg-[#FAF8F5]',
    bgCard: 'bg-white',
    bgCardHover: 'hover:bg-[#F6F5FB]',
    borderCard: 'border-[#E2DFEC]',
    textPrimary: 'text-[#2C2A29]',
    textSecondary: 'text-[#7B6B8D]',
    textMuted: 'text-[#9A96B0]',
    accentPink: '#C86D51',
    accentPinkLight: '#F5EBE6',
    accentGreen: '#5B8A72',
    accentGold: '#D97706',
    accentPurple: '#7B6B8D',
    shadowColor: 'shadow-[0px_8px_24px_rgba(44,42,41,0.04)] shadow-xl',
    bannerBg: 'bg-gradient-to-r from-[#7B6B8D] via-[#8C7D9E] to-[#A394B5]',
  },
  midnight: {
    id: 'midnight',
    name: 'Dark Utility',
    emoji: '',
    bgMain: 'bg-[#121218]',
    bgCard: 'bg-[#1B1B24]',
    bgCardHover: 'hover:bg-[#252532]',
    borderCard: 'border-[#2D2D3D]',
    textPrimary: 'text-[#F4F4F6]',
    textSecondary: 'text-[#9E9EAE]',
    textMuted: 'text-[#6A6A7C]',
    accentPink: '#C86D51',
    accentPinkLight: '#2D1E26',
    accentGreen: '#5B8A72',
    accentGold: '#F59E0B',
    accentPurple: '#7B6B8D',
    shadowColor: 'shadow-black/50 shadow-2xl',
    bannerBg: 'bg-gradient-to-r from-[#1E1B2E] via-[#2D1F45] to-[#3B2556]',
  },
};
